<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Ela" failures="0" tests="54" name="testRunner.TestRunner" time="3500.055" errors="2" timestamp="2025-06-28T14:45:41 CDT" skipped="0">
  <testcase classname="testRunner.TestRunner" name="runScenario" time="134.986"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="64.547"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="119.938"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="110.868"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="34.859"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="126.571"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="92.444"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="108.703"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="41.202"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="124.153"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="22.367"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="111.435"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="39.494"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="124.390"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="38.708"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="54.204"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="36.918"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="122.195"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="77.522"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="52.391"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="36.169"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="157.258"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="36.458"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="99.386"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="22.526"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="53.066"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="22.940"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="41.204"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="20.633"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="38.960"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="39.963"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="54.736"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="41.211"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="22.818"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="55.223">
    <error message="stale element reference: stale element not found in the current frame
  (Session info: MicrosoftEdge=137.0.3296.93)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: &#039;4.27.0&#039;, revision: &#039;d6e718d134&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;23.0.2&#039;
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [a41c98df3c741a2185bbfeebf4f6e011, isElementEnabled {id=f.82CB9180636FA7011F1F4BBAC42294EC.d.06D0760C1CB0612AB26FA4C5891467C7.e.12}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 137.0.3296.93, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:57519}, msedge: {msedgedriverVersion: 137.0.3296.93 (114b4a913acd..., userDataDir: C:\Users\ems11\AppData\Loca...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57519/devtoo..., se:cdpVersion: 137.0.3296.93, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: MicrosoftEdge on windows (a41c98df3c741a2185bbfeebf4f6e011)] -&gt; xpath: //button[@type=&#039;submit&#039;]]
Session ID: a41c98df3c741a2185bbfeebf4f6e011" type="org.openqa.selenium.StaleElementReferenceException">
      <![CDATA[org.openqa.selenium.StaleElementReferenceException: stale element reference: stale element not found in the current frame
  (Session info: MicrosoftEdge=137.0.3296.93)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Build info: version: '4.27.0', revision: 'd6e718d134'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '23.0.2'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [a41c98df3c741a2185bbfeebf4f6e011, isElementEnabled {id=f.82CB9180636FA7011F1F4BBAC42294EC.d.06D0760C1CB0612AB26FA4C5891467C7.e.12}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 137.0.3296.93, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:57519}, msedge: {msedgedriverVersion: 137.0.3296.93 (114b4a913acd..., userDataDir: C:\Users\ems11\AppData\Loca...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:57519/devtoo..., se:cdpVersion: 137.0.3296.93, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: MicrosoftEdge on windows (a41c98df3c741a2185bbfeebf4f6e011)] -> xpath: //button[@type='submit']]
Session ID: a41c98df3c741a2185bbfeebf4f6e011
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:216)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:174)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:223)
at org.openqa.selenium.remote.RemoteWebElement.isEnabled(RemoteWebElement.java:181)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
at jdk.proxy2/jdk.proxy2.$Proxy46.isEnabled(Unknown Source)
at pageObject.LoginUI_Page.isContinueWithEmailButtonEnabled(LoginUI_Page.java:66)
at stepDefinitions.Login_Step.user_should_see_sign_in_button(Login_Step.java:69)
at âœ½.User should see Sign in button(file:///C:/Users/ems11/OneDrive/Desktop/Team01_Sweet%20Debugger/Team01_SweetDebugger/src/test/resources/features/Login.feature:22)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.TestRunner" name="runScenario" time="141.099"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="40.458"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="38.771"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="99.482"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="21.029"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="34.873"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="54.707"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="35.400"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="21.588"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="52.682"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="39.141"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="98.636"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="54.735"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="22.141"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="104.270">
    <error message="Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: &#039;ELA&#039;, ip: &#039;192.168.68.65&#039;
Build info: version: &#039;4.27.0&#039;, revision: &#039;d6e718d134&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;23.0.2&#039;
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {binary: C:\Users\ems11\.cache\selen..., prefs: {remote.active-protocols: 3}}}]}]" type="org.openqa.selenium.SessionNotCreatedException">
      <![CDATA[org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 
Host info: host: 'ELA', ip: '192.168.68.65'
Build info: version: '4.27.0', revision: 'd6e718d134'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '23.0.2'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Command: [null, newSession {capabilities=[Capabilities {acceptInsecureCerts: true, browserName: firefox, moz:debuggerAddress: true, moz:firefoxOptions: {binary: C:\Users\ems11\.cache\selen..., prefs: {remote.active-protocols: 3}}}]}]
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:563)
at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:245)
at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:174)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:155)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:150)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:132)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:127)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:112)
at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:102)
at driverFactory.DriverConfig.initializeDriver(DriverConfig.java:20)
at common.TestContext.getDriver(TestContext.java:27)
at pageObject.LoginUI_Page.<init>(LoginUI_Page.java:38)
at common.TestContext.getLoginUI_Page(TestContext.java:49)
at stepDefinitions.LoginUI_Step.<init>(LoginUI_Step.java:19)
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:501)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)
at io.cucumber.picocontainer.PicoFactory.getInstance(PicoFactory.java:64)
at io.cucumber.java.AbstractGlueDefinition.invokeMethod(AbstractGlueDefinition.java:47)
at io.cucumber.java.JavaStepDefinition.execute(JavaStepDefinition.java:29)
at io.cucumber.core.runner.CoreStepDefinition.execute(CoreStepDefinition.java:66)
at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:62)
at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:81)
at io.cucumber.core.runner.TestStep.run(TestStep.java:53)
at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
at io.cucumber.testng.TestNGCucumberRunner.lambda$runScenario$1(TestNGCucumberRunner.java:135)
at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:136)
at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:136)
at io.cucumber.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:132)
at io.cucumber.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:35)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:81)
at org.testng.internal.thread.Async$AsyncTask.run(Async.java:34)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1575)
Caused by: java.io.UncheckedIOException: java.net.ConnectException
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:496)
at org.openqa.selenium.remote.http.AddSeleniumUserAgent.lambda$apply$0(AddSeleniumUserAgent.java:42)
at org.openqa.selenium.remote.http.Filter.lambda$andFinally$1(Filter.java:55)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.lambda$executeAsync$1(JdkHttpClient.java:383)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
... 3 more
Caused by: java.net.ConnectException
at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:956)
at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
at org.openqa.selenium.remote.http.jdk.JdkHttpClient.execute0(JdkHttpClient.java:455)
... 8 more
Caused by: java.net.ConnectException
at java.net.http/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1082)
at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:227)
at java.net.http/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:280)
at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$2(PlainHttpConnection.java:238)
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:978)
at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:955)
at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:554)
at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1817)
... 3 more
Caused by: java.nio.channels.ClosedChannelException
at java.base/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:204)
at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:958)
at java.net.http/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:210)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)
at java.net.http/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:212)
... 9 more
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase classname="testRunner.TestRunner" name="runScenario" time="134.857"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="35.018"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="53.620"/>
  <testcase classname="testRunner.TestRunner" name="runScenario" time="37.102"/>
</testsuite> <!-- testRunner.TestRunner -->
